[package]
name = "millo-sender"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
millo-dry-run = { path = "../millo-dry-run" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
millo-gcode = { path = "../millo-gcode" }
serde_json.workspace = true
