[package]
name = "millo-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
 millo-dry-run = { path = "../millo-dry-run" }
millo-domain = { path = "../millo-domain" }
millo-grbl = { path = "../millo-grbl" }
millo-settings = { path = "../millo-settings" }
millo-transport = { path = "../millo-transport" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
millo-mock = { path = "../millo-mock" }
