[package]
name = "millo-dry-run"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
millo-domain = { path = "../millo-domain" }
millo-gcode = { path = "../millo-gcode" }
millo-heightmap = { path = "../millo-heightmap" }
serde.workspace = true
thiserror.workspace = true
