mod commands;

use commands::{
    AppState, abort_program_run, acknowledge_reset, active_transport, adjust_feed_override,
    adjust_spindle_override, authorize_first_cut, cancel_dry_run, cancel_heightmap, cancel_jog,
    clear_surface_session, complete_tool_change, configure_script_plugin, confirm_soft_reset,
    connect_transport, controller_settings, controller_snapshot, create_cutting_tool,
    create_machine_profile, delete_cutting_tool, delete_script_plugin, detect_machine_profile,
    diagnostic_log_snapshot, disconnect, dismiss_program_recovery, execute_script_plugin,
    export_diagnostic_log, export_script_plugin, feed_hold, generate_image_job,
    generate_surfacing_job, heightmap_snapshot, import_script_plugin, inspect_device, jog_pad_step,
    list_transports, machine_profiles, mock_clear_alarm, mock_start_run, mock_trigger_alarm,
    mock_trigger_disconnect, mock_trigger_reset, mock_trigger_timeout, parse_gcode_program,
    pause_dry_run, pause_heightmap, pause_program_run, preflight_real_run,
    prepare_program_recovery, prepare_selected_program_run, prepare_test_jog, probe_z,
    program_recovery_candidate, refresh_status, request_soft_reset, restore_cutting_tool_presets,
    resume_dry_run, resume_heightmap, resume_program_run, return_to_work_zero,
    rollback_controller_setting, save_gcode_program, save_generated_gcode, save_script_plugin,
    script_plugins, select_machine_profile, sender_run_history, sender_snapshot,
    set_heightmap_application, set_rapid_override, set_work_zero, start_check_run, start_heightmap,
    start_mock_dry_run, start_program_run, step_jog, surface_session, tool_library, unlock_alarm,
    update_controller_setting, update_cutting_tool, update_machine_local_settings,
};
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let profile_path = app.path().app_config_dir()?.join("machine-profiles.json");
            app.manage(AppState::load(profile_path)?);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            controller_snapshot,
            machine_profiles,
            tool_library,
            create_cutting_tool,
            update_cutting_tool,
            delete_cutting_tool,
            restore_cutting_tool_presets,
            create_machine_profile,
            update_machine_local_settings,
            select_machine_profile,
            detect_machine_profile,
            list_transports,
            active_transport,
            connect_transport,
            controller_settings,
            update_controller_setting,
            rollback_controller_setting,
            refresh_status,
            inspect_device,
            feed_hold,
            adjust_feed_override,
            set_rapid_override,
            adjust_spindle_override,
            request_soft_reset,
            confirm_soft_reset,
            prepare_test_jog,
            step_jog,
            jog_pad_step,
            set_work_zero,
            return_to_work_zero,
            probe_z,
            surface_session,
            heightmap_snapshot,
            start_heightmap,
            pause_heightmap,
            resume_heightmap,
            cancel_heightmap,
            set_heightmap_application,
            clear_surface_session,
            parse_gcode_program,
            script_plugins,
            import_script_plugin,
            save_script_plugin,
            export_script_plugin,
            configure_script_plugin,
            delete_script_plugin,
            execute_script_plugin,
            generate_image_job,
            generate_surfacing_job,
            save_generated_gcode,
            save_gcode_program,
            preflight_real_run,
            prepare_selected_program_run,
            authorize_first_cut,
            start_program_run,
            start_check_run,
            pause_program_run,
            resume_program_run,
            abort_program_run,
            complete_tool_change,
            sender_snapshot,
            sender_run_history,
            diagnostic_log_snapshot,
            export_diagnostic_log,
            program_recovery_candidate,
            prepare_program_recovery,
            dismiss_program_recovery,
            start_mock_dry_run,
            pause_dry_run,
            resume_dry_run,
            cancel_dry_run,
            cancel_jog,
            disconnect,
            acknowledge_reset,
            unlock_alarm,
            mock_trigger_reset,
            mock_start_run,
            mock_trigger_alarm,
            mock_clear_alarm,
            mock_trigger_timeout,
            mock_trigger_disconnect
        ])
        .run(tauri::generate_context!())
        .expect("failed to run Millo");
}
